### ISSUE TITLE
Documentation nit

### ISSUE THREAD

**Issue by alixander** [cbillowes/gatsby-remark-interactive-gifs#5]
This is an excellent library, thanks for making it! 

A small documentation nit I have is that in the markdown, you should reference the gif relative to the src directory configured. I initially assumed it was relative to current markdown page (like the rest of my images are), and waddled around a little to figure that out.

**Comment by cbillowes** [comment]
Hey, I am so glad you think it's excellent. Thank you.

I am not sure why I never got a notification for this issue. I'll look into it for you.
