### ISSUE TITLE
Only process gif file types

### ISSUE THREAD

**Issue by alixander** [cbillowes/gatsby-remark-interactive-gifs#7]
This currently picks up files like `.DS_Store`, which is automatically generated on OSX, among other file types that are not gifs, which is a little restrictive on directory structure.

**Comment by cbillowes** [comment]
Thank you for your pull requests. I have merged both changes. I have made a few changes on top of yours and deployed `1.0.4` to npm. Let me know if something else needs to be done. I have done extensive testing but it would be great if you could let me know if you do pick up something wonky. Also, would you mind helping me if you know how to get `gatsby-node.js` under test?

**Comment by alixander** [comment]
Thanks for getting that updated so quickly and the maintanence. I'm actually quite new to Gatsby, so, not sure about how plugins are tested, sorry! Will post another issue if I run into anything.
